### ISSUE TITLE
Aliucord support

### ISSUE THREAD

**Issue by kipuyanoo** [Comfy-Themes/Discord#102]
Support for [Aliucord](https://github.com/Aliucord/Aliucord) would be awesome

**Comment by Maclean-D** [comment]
There is one already. If you have the theme repo plugin it should appear.

**Comment by Maclean-D** [comment]
![Screenshot_20230503-234944](https://user-images.githubusercontent.com/65423362/236131094-f8019339-48b9-4859-856d-47fbaa5eebc9.png)

**Comment by kipuyanoo** [comment]
Where do I get the Theme Repo plugin?

**Comment by NYRI4** [comment]
https://raw.githubusercontent.com/Comfy-Themes/Discord/2611761c4a7506014913bf13f51763511d4d6261/aliucord/comfy.json
