### ISSUE TITLE
Profile button placement incorrect on Vencord with "BetterFolders" enabled

### ISSUE THREAD

**Issue by Kyobinoyo** [Comfy-Themes/Discord#105]
While using the "BetterFolders" sidebar in Vencord the Profile picture/button doesn't move along.

![Discord_qWmvK26cES](https://github.com/Comfy-Themes/Discord/assets/13241508/11b8031c-7fa6-472c-864a-2834b2b98c5e)

**Comment by NYRI4** [comment]
Will be supported in next push

**Comment by T3M1N4L** [comment]
It's not fixed.
