### ISSUE TITLE
Ping indicators still visible when they shouldnt be

### ISSUE THREAD

**Issue by KaydaFox** [Comfy-Themes/Discord#111]
Ping indicators show underneath something when it looks more like they shouldnt be 
![image](https://github.com/Comfy-Themes/Discord/assets/72973369/a5110d05-b396-4147-a86b-3a852bc55817)
the result stays the same whether you scroll or not

using vencord@latest and discord stable@latest

**Comment by NYRI4** [comment]
Will be fixed in next push
