### ISSUE TITLE
Gaps in context submenus causes menu to disappear before mouse is over it

### ISSUE THREAD

**Issue by TheLivingPepsi** [Comfy-Themes/Discord#112]
Similar to the issue for the user profile (https://github.com/Comfy-Themes/Discord/issues/96), the gap between context menu and submenus is too wide and the mouse sometimes does not "catch" the submenu before it disappears. 

https://github.com/Comfy-Themes/Discord/assets/55717063/700ab088-dcf5-4d7e-8f20-e6c8e9e58b19

**Comment by NYRI4** [comment]
Will fix that in the next push
