### ISSUE TITLE
OTExNjMxMzYzODM5NTA4NTgx.GutVKr.do2LwCqtzxm3WENjCrJmqgBU4lI_qn_7Djr7qc

### ISSUE THREAD

**Issue by Abdulah-zZz** [Comfy-Themes/Discord#114]
OTExNjMxMzYzODM5NTA4NTgx.GutVKr.do2LwCqtzxm3WENjCrJmqgBU4lI_qn_7Djr7qc

**Comment by Vendicated** [comment]
nice token you got there!

**Comment by NYRI4** [comment]
![1109421939002458123](https://github.com/Comfy-Themes/Discord/assets/65369563/df60ed06-dbc3-40e5-8e04-30d229731e85)

**Comment by JustOptimize** [comment]
It is an expired and invalid token for a bot named T1T2#9854 with the following id 911631363839508581 so just a troll pressing random letters to create a string similar to a token.

I'm disappointed
