### ISSUE TITLE
user profile wave animation jumping/not looping properly on vencord

### ISSUE THREAD

**Issue by bash-ful** [Comfy-Themes/Discord#115]
I don't know if this was intentional or a bug, but the wave animation when viewing user profile jumps ahead.

https://github.com/Comfy-Themes/Discord/assets/67813011/2ef3fd51-a546-432b-87e5-7cd480ad0f70

I have tried:
- restarting discord
- removing and reapplying the theme on vencord
- rebooting the PC

all with no avail.

I am applying the theme via `vencord` on `Linux Mint 21.2`

**Comment by NYRI4** [comment]
That's surely an issue on my end, just know by the way that restarting Discord is the latest choice you could make, rebooting your computer won't change anything for themes (almost sure plugins and client mods too)

**Comment by NYRI4** [comment]
Will be fixed in the next push, thanks for the report 👍

**Comment by bash-ful** [comment]
I can confirm that the issue is fixed now on my part. Very nice
