### ISSUE TITLE
threads are indented for some reason

### ISSUE THREAD

**Issue by aaronliu0130** [Comfy-Themes/Discord#118]
![image](https://github.com/Comfy-Themes/Discord/assets/11874211/98807f97-1e74-47ac-b870-dbb9a3b3fc63)

**Comment by aaronliu0130** [comment]
![image](https://github.com/Comfy-Themes/Discord/assets/11874211/e9fd2e62-5830-42b5-9266-bce52de7edf7)
they're still indented

**Comment by NYRI4** [comment]
it's working for me ?
![image](https://github.com/Comfy-Themes/Discord/assets/65369563/7d4b7699-c45f-40a5-a993-f8f91d41fa3c)
 Do you have the latest version of Comfy ?

**Comment by aaronliu0130** [comment]
I sort of have it installed twice. Once in OpenAsar (which includes a css file so it should be auto-updating through the @import) and once in Replugged, which has the latest version of comfy

**Comment by NYRI4** [comment]
That could be an issue on your end, try to comment CSS snippets or disable some plugins that could affect threads

**Comment by aaronliu0130** [comment]
I just removed the comfy parts from openasar; it still looks like that

**Comment by aaronliu0130** [comment]
Plugins list:
```
com.cafeed28.NitroSpoof.asar
com.twoexem.delta.MMM.asar
dev.albertp.CanaryLinks.asar
dev.albertp.ChannelTyping.asar
dev.albertp.MentionCacheFix.asar
dev.albertp.NoNitroUpsell.asar
dev.albertp.RoleColorEverywhere.asar
dev.kingfish.BetterCodebIocks.asar
dev.kingfish.CopyRaw.asar
dev.kingfish.EditUtiIs.asar
dev.kingfish.Morelnvites.asar
dev.penguinspy.pronoundb.asar
dev.sammcheese.lnvisibleChat.asar
dev.tharki.ReUSRBGasar
dev.tharki.ShowHiddenChannels.asar
dev.tharki.ShowNames.asar
dev.tharki.Token.asar
dev.wolfplugs.HolyNotes.asar
lib.evelyn.SpotifyListenAlong.asar
me.puyodead1.NoReplyMention.asar
```
