### ISSUE TITLE
Text overflow in settings > vencord > plugins

### ISSUE THREAD

**Issue by dragsbruh** [Comfy-Themes/Discord#123]
I hope this is the correct place to post this but the picture below is self explanatory
![image](https://github.com/Comfy-Themes/Discord/assets/77605763/f45ce973-fa47-490f-b836-5c1c405bbbd5)

here is the full screen for reference
![image](https://github.com/Comfy-Themes/Discord/assets/77605763/f3a2f7de-3b28-44c9-adda-9edc80f66b71)

if you didn't quite get it big plugin names go out of the box.

**Comment by NYRI4** [comment]
will be fixed in the next push 👍

**Comment by NYRI4** [comment]
btw it's Comfy's repository here, not Couve

**Comment by dragsbruh** [comment]
> will be fixed in the next push 👍

Noice
