### ISSUE TITLE
Minor aesthetic problem

### ISSUE THREAD

**Issue by 016R35H** [Comfy-Themes/Discord#125]
![image](https://github.com/Comfy-Themes/Discord/assets/138529583/698297a7-8e3c-4f3a-9a21-fb89d86a929c)

As you can see, when you put those buttons vertically, the text doesn't fit and appears half cut off on the left.

**Comment by NYRI4** [comment]
https://github.com/Comfy-Themes/Discord/issues/120#issuecomment-1698057499
