### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by ffuentesm** [Comfy-Themes/Discord#127]
As you can see I have comfy theme installed, but for some reason, it stopped working last week. 
![image](https://github.com/Comfy-Themes/Discord/assets/44974827/f54e563b-94f8-41b9-bc5a-f7e38901b045)

As yo can see, it just shows normal discord theme
![image](https://github.com/Comfy-Themes/Discord/assets/44974827/22c21eb9-f338-49c2-8ae6-87492f11cdf7)

**Comment by Saltssaumure** [comment]
Caused by a Discord update, fix submitted in #128
