### ISSUE TITLE
icon shapes and toolbar won't change 

### ISSUE THREAD

**Issue by harshahuja047** [Comfy-Themes/Discord#129]
![Screenshot 2023-10-25 174811](https://github.com/Comfy-Themes/Discord/assets/83862345/35757a28-6f25-407f-95c2-461cc61a475c)
what should i do to fix this?

**Comment by ploonyplane** [comment]
Having the same issue, I am assuming this has to do with Discord's recent update.

**Comment by dopadream** [comment]
Should be fixed now. Update Vencord and if it works close this issue please

**Comment by harshahuja047** [comment]
thanks yes it's fixed
