### ISSUE TITLE
them brokeh

### ISSUE THREAD

**Issue by aaronliu0130** [Comfy-Themes/Discord#143]
![image](https://github.com/Comfy-Themes/Discord/assets/11874211/c571b486-6a21-43d6-8af2-3c8134bf8580)

**Comment by MixingSneaX** [comment]
Same issue, only a few small things like color and in SOME cases the round square profiles are still working

**Comment by necromancerpigeon** [comment]
same for me

**Comment by aaronliu0130** [comment]
use reactions my people
