### ISSUE TITLE
Dropdowns always open down

### ISSUE THREAD

**Issue by CatThingy** [Comfy-Themes/Discord#30]
Vanilla dropdowns open either up or down based on the space available:
<details>
<summary>Space below</summary>

![image](https://user-images.githubusercontent.com/32040424/129466170-60d228df-5b56-40ec-ab8a-699fce24ce2c.png)
</details>

<details>
<summary>No space below</summary>

![image](https://user-images.githubusercontent.com/32040424/129466215-77d7923f-1125-4775-8b7a-310ce9b92034.png)
</details>

This breaks with the theme applied:
<details>
<summary>Space below</summary>

![image](https://user-images.githubusercontent.com/32040424/129466258-a31119cc-3e95-4af5-8235-d12ec5369114.png)

</details>

<details>
<summary>No space below</summary>

![image](https://user-images.githubusercontent.com/32040424/129466268-dcd93a2c-9a36-466f-ab06-1f8d29517991.png)

On clicking the dropdown again, everything shifts upwards to make more space for it:

![image](https://user-images.githubusercontent.com/32040424/129466285-dd1acd00-90e4-4c19-a0c9-d7f5041820c1.png)

</details>

**Comment by NYRI4** [comment]
I guess that's a bot feature you're showing here, if you mind sending a public one that have dropdowns like that, it would be cool
