### ISSUE TITLE
User Settings getting cut off

### ISSUE THREAD

**Issue by Absumm** [Comfy-Themes/Discord#51]
User settings text gets cut off 
![image](https://user-images.githubusercontent.com/56665292/150020574-01126387-86ed-4fa3-86d2-e71f324340e7.png)
![image](https://user-images.githubusercontent.com/56665292/150020585-2b9eafe9-3dab-4bc5-a116-cd8701985598.png)

**Comment by NYRI4** [comment]
This can't be fixed sadly

**Comment by Absumm** [comment]
is there way to make it just say setting or something? I personally find it a bit annoying lol

**Comment by Loremly** [comment]
You can get the exact tooltip using debugger, then make the color transparent, size it, move it. Make a pseudo element that adds a text. And there.

**Comment by Loremly** [comment]
Or just leave it alone

**Comment by MichaelDavidGK** [comment]
Can be fixed with (if you know how):
`overflow-wrap: break-word; `
