### ISSUE TITLE
Minor alignment bug

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Comfy-Themes/Discord#53]
Due to the api error this bug is evident, since this basically never happens, its not really necessary to fix, but the alignment on the fancy new loading icon is not centered.

![image](https://user-images.githubusercontent.com/62061444/151242860-f401fe2f-fbed-4943-99b0-141f5defbc65.png)

**Comment by TranquillyUnpleasant** [comment]
Also i haven't mentioned this but the animation for the loading screen is gorgeous, absolutely love it.

**Comment by NYRI4** [comment]
too lazy
