### ISSUE TITLE
how to change discord status icons from square to regular

### ISSUE THREAD

**Issue by COD1EINE** [Comfy-Themes/Discord#58]
hi ik this isn't the place i shouldn't ask but since ur the theme dev i'd thought u'd know how to change the discord status icons from square to normal.  i tried doing it myself by removing all of the code for the status. 
<img width="37" alt="DiscordCanary_Vgcdcpzvc9" src="https://user-images.githubusercontent.com/89225155/161990228-946706ed-b094-4403-8bf3-58189b61d59c.png">
as u can see it didn't work :/

**Comment by kusogakinerd** [comment]
![image](https://user-images.githubusercontent.com/103561040/163161828-b7aad237-8852-4115-88aa-e1447afc488b.png)
change value of status more than 3px
