### ISSUE TITLE
Banners on profile view are bugged

### ISSUE THREAD

**Issue by Absumm** [Comfy-Themes/Discord#62]
![image](https://user-images.githubusercontent.com/56665292/166862608-df6cc473-0f0b-45ba-8a47-3820853c6bb8.png)
![image](https://user-images.githubusercontent.com/56665292/166862625-6cc0f3f5-14d1-425b-aa18-1c1272b7ed49.png)

**Comment by Wayyllon** [comment]
me watching comfy di e

**Comment by Absumm** [comment]
has been fixed(?) by me, still looks a little weird but I have limited knowledge of this all

**Comment by Absumm** [comment]
re-opening so people can see

**Comment by Nobodyno-boop** [comment]
Hi, for me just change `:root .root-8LYsGj` from 700 to 590 work.


in main.css
```css
:root .root-8LYsGj {
  width: 590px; /* from 700 to 590 */
}
```
