### ISSUE TITLE
Broken status menu

### ISSUE THREAD

**Issue by TsukiruP** [Comfy-Themes/Discord#63]
Discord's default status menu shows up no matter the theme. Which means it covers up the attachment button and is just overall ugly.

![image](https://user-images.githubusercontent.com/104665617/168392653-75d25ba6-032a-448d-b97a-968bebfb5f20.png)

Worth mentioning that also the notification icons appear over the call and settings buttons when the server list is long enough.
![image](https://user-images.githubusercontent.com/104665617/168392848-dd7cd70f-4b40-41b4-97a1-a3932ce154a1.png)

**Comment by NYRI4** [comment]
Tell me if still does it with this update : https://github.com/Comfy-Themes/Discord/commit/376c0f13766de2392dab416038238f8a8c071921

**Comment by TsukiruP** [comment]
Sorry, neglected to say everything has been fine since.
