### ISSUE TITLE
Horizontal server list

### ISSUE THREAD

**Issue by teoshibin** [Comfy-Themes/Discord#68]
What I did is enabling 2 themes (Comfy and horizontal server list) just to test it out.
Additional customization for horizontal server list within this theme?

![image](https://user-images.githubusercontent.com/62151367/171384502-978c72d0-d323-4f9d-886c-71b808f2188a.png)

**Comment by NYRI4** [comment]
The problem is that for the moment a theme cannot know if another one have been enabled or not
