### ISSUE TITLE
[BUG] Status selector is broken

### ISSUE THREAD

**Issue by Juknum** [Comfy-Themes/Discord#71]
When I click on the status button, It's a bit broken :§
![image](https://user-images.githubusercontent.com/49886317/173253737-de946600-df1b-4c59-a4a9-3eb7da3fb04b.png)

**Comment by Alicyl** [comment]
How do you even get to this? I can't find it anywhere on mine.

**Comment by NYRI4** [comment]
I suppose that this issue has been fixed by now, if that's not the case you're welcome to open it again
