### ISSUE TITLE
[BUG] Button become invisible when hovered

### ISSUE THREAD

**Issue by Juknum** [Comfy-Themes/Discord#73]
The "invite" button present in the "invite people" section in hubs, become transparent when hovered, rather than being darkened
![image](https://user-images.githubusercontent.com/49886317/173254185-5774e599-93d5-4764-b56b-99e2827c733d.png)
![image](https://user-images.githubusercontent.com/49886317/173254146-e49b72b5-ce34-4922-b3ab-0da72897658b.png)

**Comment by NYRI4** [comment]
Fixed already
