### ISSUE TITLE
Comfy Theme broken on Replugged/Powercord

### ISSUE THREAD

**Issue by nikander100** [Comfy-Themes/Discord#77]
I saw in the last commit 2c21ad6 the manifest file's that are used by a still working Powercord and community version Replugged have been removed and breaking the theme for people. Could this be reverted or is comfy not supporting powercord/replugged anymore.

**Comment by NYRI4** [comment]
Surely, just a mistake

**Comment by makerio90** [comment]
theme still works fine once the files are added back.

**Comment by lucawen** [comment]
still not fixed

**Comment by nikander100** [comment]
> still not fixed

noticed that, i hope the dev/maintainer will add the files back to the release branch.

**Comment by makerio90** [comment]
fixed #79
