### ISSUE TITLE
Banners broke (again)

### ISSUE THREAD

**Issue by Absumm** [Comfy-Themes/Discord#80]
![image](https://user-images.githubusercontent.com/56665292/188086596-04c37061-e0ad-423b-a36e-127e9bc6c4f7.png)

any fixes?

**Comment by NYRI4** [comment]
Can you give more information on which client you're using and is it the nitro / USRBG one, beucaise in my end all is working

**Comment by CallOfJuarez** [comment]
Appears to be broken for me as well:
![Screenshot 2022-09-12 153744](https://user-images.githubusercontent.com/81934509/189670079-5ac74006-ee59-4d2b-8582-6c9d084d9566.png)

From bottom of settings:
Stable 146284 (57b3d6d)
BetterDiscord 1.6.3
Host 1.0.9006
Windows 10 64-Bit (10.0.22000)

**Comment by NYRI4** [comment]
Apparently this is the new profile thing being rolled to some of you guys, since I don't have Nitro and the update itself, I can't do anything from now
