### ISSUE TITLE
Comfy's Search Bar Behavior

### ISSUE THREAD

**Issue by Alicyl** [Comfy-Themes/Discord#82]
I don't know if this is intended or if it's a bug, but if it is intended, can we please back this set back to its default behavior?

Whenever I have it selected with the intent to type in it, it closes itself anyway when I move the cursor away from it which prevents me from seeing what I'm typing unless I keep the cursor there. This also prevents me from using my cursor to check other things inside or outside of Discord relevant to what I'm trying to type in the search bar.

Comfy's Search Bar Behavior
![Discord_g8HZh7Bsvj](https://user-images.githubusercontent.com/13776859/190045707-514c7189-497c-45df-8231-5982de75c0f5.gif)

Default Search Bar Behavior
![msedge_G2rRhRWZfU](https://user-images.githubusercontent.com/13776859/190045939-f8290f91-fcf5-4184-9d17-0d2c272339ca.gif)

**Comment by SiJiL82** [comment]
Ctrl + F also doesn't show the search bar, even though the focus moves to it and you can type in it - you just can't see what you're typing.

**Comment by NYRI4** [comment]
Fixed
