### ISSUE TITLE
User Status not in the Correct Spot on the Text Line

### ISSUE THREAD

**Issue by Deathninja5551** [Comfy-Themes/Discord#89]
![Screenshot 2023-02-11 173431](https://user-images.githubusercontent.com/97482815/218283927-1cc48a90-1441-4b9b-80a4-3157fe28021c.png)
Changed settings from default:
No scrollbars set to Disabled
Better SpotifyControls seek bar set to Disabled
Animations set to Disabled
User buttons set to 4px
User buttons color changed
Avatar radius set to 0px
Status radius set to 25px
server radius set to 0px
background color changed

**Comment by Deathninja5551** [comment]
Restart resolved this issue.

**Comment by Deathninja5551** [comment]
Issue happens again when status is changed.
aaauuugghh
Have tested with no plugins.

**Comment by Deathninja5551** [comment]
Changing status caused this issue again.

**Comment by NYRI4** [comment]
Should be fixed in the next push
