### ISSUE TITLE
Channels and Pings not Directed at you are Highlighted as Pings Towards you

### ISSUE THREAD

**Issue by Deathninja5551** [Comfy-Themes/Discord#92]
Messages with channel names being highlighted
![1](https://user-images.githubusercontent.com/97482815/220609795-2fdf9f6d-7536-41f0-929a-af958f590e2b.png)
Message with a ping not directed at me being highlighted
![2](https://user-images.githubusercontent.com/97482815/220609927-b7804bbc-ffd9-4e69-bef3-4f61742a49da.png)
Message with a **ping directed at me** being ~~double~~ highlighted
![3](https://user-images.githubusercontent.com/97482815/220609985-93afb32d-6b9a-46d2-961e-c474c8b84a5a.png)

**Comment by Deathninja5551** [comment]
This does not appear to be tied to the『 Mention colors in chat 』setting.
![4](https://user-images.githubusercontent.com/97482815/220611611-d4120ffe-ed81-43d8-955a-9da73b0c065e.png)
The blue is still visible through the red.

**Comment by NYRI4** [comment]
Fixed in the next push
