### ISSUE TITLE
Many Icons Ignore Roundness Settings

### ISSUE THREAD

**Issue by Deathninja5551** [Comfy-Themes/Discord#94]
Server icons, DM icons, Profile icons, and the Status icon are permanently round. Additionally, the status icon has a new issue: #93.
Servers in folders and Chat icons keep the roundness setting.

**Comment by Deathninja5551** [comment]
The Member List is also round.

**Comment by NYRI4** [comment]
Discord recently changed a bunch of classes Ill get into it soon

**Comment by NYRI4** [comment]
Should be fixed in the next push
