### ISSUE TITLE
Space between your own profile and the "dropdowns" too wide, trapping mouse before it hovers over the options

### ISSUE THREAD

**Issue by aaronliu0130** [Comfy-Themes/Discord#96]
https://user-images.githubusercontent.com/11874211/229657330-ffa3223c-2499-4e0d-b38b-6dec23ead711.mp4

This forces us to memorize some specific speed so we can consistently get to the dropdown. Could either add add a capture zone there if possible or shorten the gap.

**Comment by NYRI4** [comment]
Done

**Comment by aaronliu0130** [comment]
@NYRI4 a similar thing exists for editing tags for forums
![image](https://github.com/Comfy-Themes/Discord/assets/11874211/9d2482c1-ed1b-462f-be71-fe7904ccdf9d)
