### ISSUE TITLE
A few minor issues (All for Comfy Theme)

### ISSUE THREAD

**Issue by xaWolff** [Comfy-Themes/Discord#99]
Issue 1: When I use the theme, if there's 2 images in 1 message the background isn't transparent. It shows as transparent like normal with only 1 image though. 
![image](https://user-images.githubusercontent.com/122491447/232674000-13a274f5-a0a3-4c48-8b62-30ef1c6ba9a4.png)

Issue 2: There's a small diagonal line from top left to bottom right when focusing someone in a call.
![image](https://user-images.githubusercontent.com/122491447/232674103-1b758db6-8530-4f23-a886-9ccd23cb85dc.png)

Issue 3: The user preview in the profiles section is all misaligned and kind of broken.
![image](https://user-images.githubusercontent.com/122491447/232674190-6288d5a0-b814-4667-9f0b-95c98cfb6bb8.png)

Sorry to bother but thank you for the great theme

**Comment by NYRI4** [comment]
Issue 1/3 : Fixed
Issue 2  : Discord's fault
